# Generated by Django 5.0.3 on 2024-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='announcement',
            table=None,
        ),
    ]
