# Generated by Django 5.0.3 on 2024-04-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_user_alter_customuser_age_alter_customuser_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Creator_id", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Ad",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
