# Generated by Django 5.0.3 on 2024-04-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_advertisement_delete_ad_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("requirements", models.TextField()),
                ("how_many", models.IntegerField()),
                ("creation_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
