# Generated by Django 5.0.3 on 2024-07-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='number_of_announcements',
        ),
    ]
