# Generated by Django 5.0.3 on 2024-05-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_announcement_creator_id_announcement_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='owner',
            new_name='user',
        ),
    ]
