# Generated by Django 5.0.3 on 2024-05-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
    ]
