# Generated by Django 5.0.3 on 2024-06-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_skillname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='SoftSkillName',
        ),
    ]
